--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-06-19 17:57:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 58164)
-- Name: ForkliftDowntimes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ForkliftDowntimes" (
    "Id" integer NOT NULL,
    "ForkliftId" integer NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "Description" character varying(100)
);


ALTER TABLE public."ForkliftDowntimes" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 58163)
-- Name: ForkliftDowntimes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ForkliftDowntimes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ForkliftDowntimes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 58156)
-- Name: Forklifts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Forklifts" (
    "Id" integer NOT NULL,
    "Brand" character varying(50) NOT NULL,
    "Number" character varying(50) NOT NULL,
    "LoadCapacity" numeric(10,2) NOT NULL,
    "isActive" boolean NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" text NOT NULL
);


ALTER TABLE public."Forklifts" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 58155)
-- Name: Forklifts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Forklifts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Forklifts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 58150)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4807 (class 0 OID 58164)
-- Dependencies: 221
-- Data for Name: ForkliftDowntimes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ForkliftDowntimes" ("Id", "ForkliftId", "StartTime", "EndTime", "Description") FROM stdin;
11	2	2025-06-19 10:09:00+03	\N	сломался
3	4	2025-06-17 10:34:00+03	2025-06-21 11:00:00+03	Поломка
7	5	2025-06-18 11:05:00+03	\N	Сломался
10	10	2025-06-18 08:35:00+03	2025-06-20 09:35:00+03	Поломка. Требуется техобслуживание
\.


--
-- TOC entry 4805 (class 0 OID 58156)
-- Dependencies: 219
-- Data for Name: Forklifts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Forklifts" ("Id", "Brand", "Number", "LoadCapacity", "isActive", "UpdatedAt", "UpdatedBy") FROM stdin;
4	Амкадор	11-92 PM-2	1.50	t	2025-06-19 14:50:42.856137+03	Василий
5	Heli	1123 HH-5	2.50	f	2025-06-19 14:52:28.830679+03	Петров А.А.
11	Амкадор	9875 PP-1	5.70	t	2025-06-19 14:53:07.345654+03	Петров А.А
10	Everun	1234 AM-5	4.54	t	2025-06-19 14:53:36.944902+03	Владимир
2	Lonking	45-65 PH-1	2.50	f	2025-06-19 14:53:51.13949+03	Иванов
9	TCM	3311 PB-2	4.50	t	2025-06-19 14:54:08.019118+03	Иванов И.И.
\.


--
-- TOC entry 4803 (class 0 OID 58150)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250618084535_InitialMigration	9.0.6
20250618110403_UpdateEndTime	9.0.6
\.


--
-- TOC entry 4813 (class 0 OID 0)
-- Dependencies: 220
-- Name: ForkliftDowntimes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ForkliftDowntimes_Id_seq"', 15, true);


--
-- TOC entry 4814 (class 0 OID 0)
-- Dependencies: 218
-- Name: Forklifts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Forklifts_Id_seq"', 14, true);


--
-- TOC entry 4656 (class 2606 OID 58168)
-- Name: ForkliftDowntimes PK_ForkliftDowntimes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ForkliftDowntimes"
    ADD CONSTRAINT "PK_ForkliftDowntimes" PRIMARY KEY ("Id");


--
-- TOC entry 4653 (class 2606 OID 58162)
-- Name: Forklifts PK_Forklifts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Forklifts"
    ADD CONSTRAINT "PK_Forklifts" PRIMARY KEY ("Id");


--
-- TOC entry 4651 (class 2606 OID 58154)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4654 (class 1259 OID 58174)
-- Name: IX_ForkliftDowntimes_ForkliftId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ForkliftDowntimes_ForkliftId" ON public."ForkliftDowntimes" USING btree ("ForkliftId");


--
-- TOC entry 4657 (class 2606 OID 58169)
-- Name: ForkliftDowntimes FK_ForkliftDowntimes_Forklifts_ForkliftId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ForkliftDowntimes"
    ADD CONSTRAINT "FK_ForkliftDowntimes_Forklifts_ForkliftId" FOREIGN KEY ("ForkliftId") REFERENCES public."Forklifts"("Id") ON DELETE RESTRICT;


-- Completed on 2025-06-19 17:57:45

--
-- PostgreSQL database dump complete
--

